name: Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    strategy:
      matrix:
        cfg:
        - { platform: linux, platform_name: Linux,  os: ubuntu-latest }
        - { platform: mac, platform_name: macOS, os: macos-latest }
        - { platform: win, platform_name: Windows, os: windows-latest }

    name: '${{ matrix.cfg.platform_name }} installer'
    runs-on: ${{ matrix.cfg.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1

      - name: Install dependencies
        run: |
          conda install -c conda-forge constructor

      - name: Create Application Server Installer
        run: |
          constructor .

      - name: Upload Linux Installer
        if: matrix.cfg.platform == 'linux'
        uses: actions/upload-artifact@v2
        with:
          name: linux-installer
          path: |
            Mosaic-*.sh

      - name: Upload macOS Installer
        if: matrix.cfg.platform == 'mac'
        uses: actions/upload-artifact@v2
        with:
          name: mac-installer
          path: |
            Mosaic-*.sh

      - name: Upload Windows Installer
        if: matrix.cfg.platform == 'win'
        uses: actions/upload-artifact@v2
        with:
          name: windows-installer
          path: |
            Mosaic-*.exe
